export const HISTORY_OFFERS_PROCESSING = "HISTORY_OFFERS_PROCESSING";

export const SET_HISTORY_OFFERS = "SET_HISTORY_OFFERS";

export const STOP_SET_HISTORY_OFFERS_PROCESSING = "STOP_SET_HISTORY_OFFERS_PROCESSING";
