export const BALANCE_PROCESSING = "BALANCE_PROCESSING";

export const SET_BALANCE = "SET_BALANCE";
export const SET_BALANCE_EMPTY = "SET_BALANCE_EMPTY";

export const STOP_BALANCE_PROCESSING = "STOP_BALANCE_PROCESSING";
