export const PAYMENT_QR_CODE_PROCESSING = "PAYMENT_QR_CODE_PROCESSING";

export const SET_PAYMENT_QR_CODE = "SET_PAYMENT_QR_CODE";
export const PAYMENT_QR_CODE_DISCONNECT = "PAYMENT_QR_CODE_DISCONNECT";

export const STOP_PAYMENT_QR_CODE_PROCESSING =
	"STOP_PAYMENT_QR_CODE_PROCESSING";
