export const QR_CODE_PROCESSING = "QR_CODE_PROCESSING";

export const SET_QR_CODE = "SET_QR_CODE";
export const QR_CODE_DISCONNECT = "QR_CODE_DISCONNECT";

export const STOP_QR_CODE_PROCESSING = "STOP_QR_CODE_PROCESSING";
