export const PAYMENT_RESPONSE_PROCESSING = "PAYMENT_RESPONSE_PROCESSING";

export const SET_PAYMENT_RESPONSE = "SET_PAYMENT_RESPONSE";

export const STOP_PAYMENT_RESPONSE_PROCESSING =
	"STOP_PAYMENT_RESPONSE_PROCESSING";
